# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/diy-stable-diffusion',
                'doc_host': 'https://dsikkema.github.io',
                'git_url': 'https://github.com/dsikkema/diy-stable-diffusion',
                'lib_path': 'diy_stable_diffusion'},
  'syms': { 'diy_stable_diffusion.accel': { 'diy_stable_diffusion.accel.AccelerateCB': ( '17 copy ddpmv2 mixedprecision.html#acceleratecb',
                                                                                         'diy_stable_diffusion/accel.py'),
                                            'diy_stable_diffusion.accel.AccelerateCB.__init__': ( '17 copy ddpmv2 '
                                                                                                  'mixedprecision.html#acceleratecb.__init__',
                                                                                                  'diy_stable_diffusion/accel.py'),
                                            'diy_stable_diffusion.accel.AccelerateCB.backward': ( '17 copy ddpmv2 '
                                                                                                  'mixedprecision.html#acceleratecb.backward',
                                                                                                  'diy_stable_diffusion/accel.py'),
                                            'diy_stable_diffusion.accel.AccelerateCB.before_fit': ( '17 copy ddpmv2 '
                                                                                                    'mixedprecision.html#acceleratecb.before_fit',
                                                                                                    'diy_stable_diffusion/accel.py'),
                                            'diy_stable_diffusion.accel.MixedPrecision': ( '17 copy ddpmv2 '
                                                                                           'mixedprecision.html#mixedprecision',
                                                                                           'diy_stable_diffusion/accel.py'),
                                            'diy_stable_diffusion.accel.MixedPrecision.after_loss': ( '17 copy ddpmv2 '
                                                                                                      'mixedprecision.html#mixedprecision.after_loss',
                                                                                                      'diy_stable_diffusion/accel.py'),
                                            'diy_stable_diffusion.accel.MixedPrecision.backward': ( '17 copy ddpmv2 '
                                                                                                    'mixedprecision.html#mixedprecision.backward',
                                                                                                    'diy_stable_diffusion/accel.py'),
                                            'diy_stable_diffusion.accel.MixedPrecision.before_batch': ( '17 copy ddpmv2 '
                                                                                                        'mixedprecision.html#mixedprecision.before_batch',
                                                                                                        'diy_stable_diffusion/accel.py'),
                                            'diy_stable_diffusion.accel.MixedPrecision.before_fit': ( '17 copy ddpmv2 '
                                                                                                      'mixedprecision.html#mixedprecision.before_fit',
                                                                                                      'diy_stable_diffusion/accel.py'),
                                            'diy_stable_diffusion.accel.MixedPrecision.step': ( '17 copy ddpmv2 '
                                                                                                'mixedprecision.html#mixedprecision.step',
                                                                                                'diy_stable_diffusion/accel.py')},
            'diy_stable_diffusion.activations': { 'diy_stable_diffusion.activations.ActivationStats': ( '10 copy '
                                                                                                        'activations.html#activationstats',
                                                                                                        'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.ActivationStats.__init__': ( '10 copy '
                                                                                                                 'activations.html#activationstats.__init__',
                                                                                                                 'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.ActivationStats.color_dim': ( '10 copy '
                                                                                                                  'activations.html#activationstats.color_dim',
                                                                                                                  'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.ActivationStats.dead_chart': ( '10 copy '
                                                                                                                   'activations.html#activationstats.dead_chart',
                                                                                                                   'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.ActivationStats.plot_stats': ( '10 copy '
                                                                                                                   'activations.html#activationstats.plot_stats',
                                                                                                                   'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.Hook': ( '10 copy activations.html#hook',
                                                                                             'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.Hook.__del__': ( '10 copy '
                                                                                                     'activations.html#hook.__del__',
                                                                                                     'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.Hook.__init__': ( '10 copy '
                                                                                                      'activations.html#hook.__init__',
                                                                                                      'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.Hook.remove': ( '10 copy activations.html#hook.remove',
                                                                                                    'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.Hooks': ( '10 copy activations.html#hooks',
                                                                                              'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.Hooks.__del__': ( '10 copy '
                                                                                                      'activations.html#hooks.__del__',
                                                                                                      'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.Hooks.__delitem__': ( '10 copy '
                                                                                                          'activations.html#hooks.__delitem__',
                                                                                                          'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.Hooks.__enter__': ( '10 copy '
                                                                                                        'activations.html#hooks.__enter__',
                                                                                                        'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.Hooks.__exit__': ( '10 copy '
                                                                                                       'activations.html#hooks.__exit__',
                                                                                                       'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.Hooks.__init__': ( '10 copy '
                                                                                                       'activations.html#hooks.__init__',
                                                                                                       'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.Hooks.remove': ( '10 copy '
                                                                                                     'activations.html#hooks.remove',
                                                                                                     'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.HooksCallback': ( '10 copy '
                                                                                                      'activations.html#hookscallback',
                                                                                                      'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.HooksCallback.__init__': ( '10 copy '
                                                                                                               'activations.html#hookscallback.__init__',
                                                                                                               'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.HooksCallback.__iter__': ( '10 copy '
                                                                                                               'activations.html#hookscallback.__iter__',
                                                                                                               'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.HooksCallback.__len__': ( '10 copy '
                                                                                                              'activations.html#hookscallback.__len__',
                                                                                                              'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.HooksCallback._hookfunc': ( '10 copy '
                                                                                                                'activations.html#hookscallback._hookfunc',
                                                                                                                'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.HooksCallback.after_fit': ( '10 copy '
                                                                                                                'activations.html#hookscallback.after_fit',
                                                                                                                'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.HooksCallback.before_fit': ( '10 copy '
                                                                                                                 'activations.html#hookscallback.before_fit',
                                                                                                                 'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.append_stats': ( '10 copy '
                                                                                                     'activations.html#append_stats',
                                                                                                     'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.get_hist': ( '10 copy activations.html#get_hist',
                                                                                                 'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.get_min': ( '10 copy activations.html#get_min',
                                                                                                'diy_stable_diffusion/activations.py'),
                                                  'diy_stable_diffusion.activations.set_seed': ( '10 copy activations.html#set_seed',
                                                                                                 'diy_stable_diffusion/activations.py')},
            'diy_stable_diffusion.attention': { 'diy_stable_diffusion.attention.CondEmbUNetModel': ( '28 copy attention '
                                                                                                     'only.html#condembunetmodel',
                                                                                                     'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.CondEmbUNetModel.__init__': ( '28 copy attention '
                                                                                                              'only.html#condembunetmodel.__init__',
                                                                                                              'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.CondEmbUNetModel.forward': ( '28 copy attention '
                                                                                                             'only.html#condembunetmodel.forward',
                                                                                                             'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.DownBlock': ( '28 copy attention only.html#downblock',
                                                                                              'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.DownBlock.__init__': ( '28 copy attention '
                                                                                                       'only.html#downblock.__init__',
                                                                                                       'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.DownBlock.forward': ( '28 copy attention '
                                                                                                      'only.html#downblock.forward',
                                                                                                      'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.EmbResBlock': ( '28 copy attention only.html#embresblock',
                                                                                                'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.EmbResBlock.__init__': ( '28 copy attention '
                                                                                                         'only.html#embresblock.__init__',
                                                                                                         'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.EmbResBlock.forward': ( '28 copy attention '
                                                                                                        'only.html#embresblock.forward',
                                                                                                        'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.EmbUNetModel': ( '28 copy attention only.html#embunetmodel',
                                                                                                 'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.EmbUNetModel.__init__': ( '28 copy attention '
                                                                                                          'only.html#embunetmodel.__init__',
                                                                                                          'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.EmbUNetModel.forward': ( '28 copy attention '
                                                                                                         'only.html#embunetmodel.forward',
                                                                                                         'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.SelfAttention2D': ( '28 copy attention '
                                                                                                    'only.html#selfattention2d',
                                                                                                    'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.SelfAttention2D.__init__': ( '28 copy attention '
                                                                                                             'only.html#selfattention2d.__init__',
                                                                                                             'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.SelfAttention2D._to_batch': ( '28 copy attention '
                                                                                                              'only.html#selfattention2d._to_batch',
                                                                                                              'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.SelfAttention2D._to_heads': ( '28 copy attention '
                                                                                                              'only.html#selfattention2d._to_heads',
                                                                                                              'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.SelfAttention2D.forward': ( '28 copy attention '
                                                                                                            'only.html#selfattention2d.forward',
                                                                                                            'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.UpBlock': ( '28 copy attention only.html#upblock',
                                                                                            'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.UpBlock.__init__': ( '28 copy attention '
                                                                                                     'only.html#upblock.__init__',
                                                                                                     'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.UpBlock.forward': ( '28 copy attention '
                                                                                                    'only.html#upblock.forward',
                                                                                                    'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.abar': ( '28 copy attention only.html#abar',
                                                                                         'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.collate_noised': ( '28 copy attention '
                                                                                                   'only.html#collate_noised',
                                                                                                   'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.cond_sample': ( '28 copy attention only.html#cond_sample',
                                                                                                'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.ddim_step': ( '28 copy attention only.html#ddim_step',
                                                                                              'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.diffusion_class_collate': ( '28 copy attention '
                                                                                                            'only.html#diffusion_class_collate',
                                                                                                            'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.dl': ( '28 copy attention only.html#dl',
                                                                                       'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.inv_abar': ( '28 copy attention only.html#inv_abar',
                                                                                             'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.lin': ( '28 copy attention only.html#lin',
                                                                                        'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.noisify': ( '28 copy attention only.html#noisify',
                                                                                            'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.pre_conv': ( '28 copy attention only.html#pre_conv',
                                                                                             'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.sample': ( '28 copy attention only.html#sample',
                                                                                           'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.saved': ( '28 copy attention only.html#saved',
                                                                                          'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.timestep_embedding': ( '28 copy attention '
                                                                                                       'only.html#timestep_embedding',
                                                                                                       'diy_stable_diffusion/attention.py'),
                                                'diy_stable_diffusion.attention.upsample_and_conv': ( '28 copy attention '
                                                                                                      'only.html#upsample_and_conv',
                                                                                                      'diy_stable_diffusion/attention.py')},
            'diy_stable_diffusion.augment': { 'diy_stable_diffusion.augment.CapturePreds': ( '14 copy data augmentation.html#capturepreds',
                                                                                             'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment.CapturePreds.after_batch': ( '14 copy data '
                                                                                                         'augmentation.html#capturepreds.after_batch',
                                                                                                         'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment.CapturePreds.before_fit': ( '14 copy data '
                                                                                                        'augmentation.html#capturepreds.before_fit',
                                                                                                        'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment.RandCopy': ( '14 copy data augmentation.html#randcopy',
                                                                                         'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment.RandCopy.__init__': ( '14 copy data '
                                                                                                  'augmentation.html#randcopy.__init__',
                                                                                                  'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment.RandCopy.forward': ( '14 copy data '
                                                                                                 'augmentation.html#randcopy.forward',
                                                                                                 'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment.RandErase': ( '14 copy data augmentation.html#randerase',
                                                                                          'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment.RandErase.__init__': ( '14 copy data '
                                                                                                   'augmentation.html#randerase.__init__',
                                                                                                   'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment.RandErase.forward': ( '14 copy data '
                                                                                                  'augmentation.html#randerase.forward',
                                                                                                  'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment._flops': ( '14 copy data augmentation.html#_flops',
                                                                                       'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment._rand_copy1': ( '14 copy data augmentation.html#_rand_copy1',
                                                                                            'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment._rand_erase1': ( '14 copy data augmentation.html#_rand_erase1',
                                                                                             'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment.capture_preds': ( '14 copy data '
                                                                                              'augmentation.html#capture_preds',
                                                                                              'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment.rand_copy': ( '14 copy data augmentation.html#rand_copy',
                                                                                          'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment.rand_erase': ( '14 copy data augmentation.html#rand_erase',
                                                                                           'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment.show_image_batch': ( '14 copy data '
                                                                                                 'augmentation.html#show_image_batch',
                                                                                                 'diy_stable_diffusion/augment.py'),
                                              'diy_stable_diffusion.augment.summary': ( '14 copy data augmentation.html#summary',
                                                                                        'diy_stable_diffusion/augment.py')},
            'diy_stable_diffusion.conv': { 'diy_stable_diffusion.conv.collate_device': ( '07 copy convolutions.html#collate_device',
                                                                                         'diy_stable_diffusion/conv.py'),
                                           'diy_stable_diffusion.conv.conv': ( '07 copy convolutions.html#conv',
                                                                               'diy_stable_diffusion/conv.py'),
                                           'diy_stable_diffusion.conv.to_device': ( '07 copy convolutions.html#to_device',
                                                                                    'diy_stable_diffusion/conv.py')},
            'diy_stable_diffusion.datasets': { 'diy_stable_diffusion.datasets.DataLoaders': ( '05 copy datasets.html#dataloaders',
                                                                                              'diy_stable_diffusion/datasets.py'),
                                               'diy_stable_diffusion.datasets.DataLoaders.__init__': ( '05 copy '
                                                                                                       'datasets.html#dataloaders.__init__',
                                                                                                       'diy_stable_diffusion/datasets.py'),
                                               'diy_stable_diffusion.datasets.DataLoaders.from_dd': ( '05 copy '
                                                                                                      'datasets.html#dataloaders.from_dd',
                                                                                                      'diy_stable_diffusion/datasets.py'),
                                               'diy_stable_diffusion.datasets.collate_dict': ( '05 copy datasets.html#collate_dict',
                                                                                               'diy_stable_diffusion/datasets.py'),
                                               'diy_stable_diffusion.datasets.get_grid': ( '05 copy datasets.html#get_grid',
                                                                                           'diy_stable_diffusion/datasets.py'),
                                               'diy_stable_diffusion.datasets.inplace': ( '05 copy datasets.html#inplace',
                                                                                          'diy_stable_diffusion/datasets.py'),
                                               'diy_stable_diffusion.datasets.show_image': ( '05 copy datasets.html#show_image',
                                                                                             'diy_stable_diffusion/datasets.py'),
                                               'diy_stable_diffusion.datasets.show_images': ( '05 copy datasets.html#show_images',
                                                                                              'diy_stable_diffusion/datasets.py'),
                                               'diy_stable_diffusion.datasets.subplots': ( '05 copy datasets.html#subplots',
                                                                                           'diy_stable_diffusion/datasets.py')},
            'diy_stable_diffusion.fid': { 'diy_stable_diffusion.fid.ImageEval': ( '18 copy fid.html#imageeval',
                                                                                  'diy_stable_diffusion/fid.py'),
                                          'diy_stable_diffusion.fid.ImageEval.__init__': ( '18 copy fid.html#imageeval.__init__',
                                                                                           'diy_stable_diffusion/fid.py'),
                                          'diy_stable_diffusion.fid.ImageEval.fid': ( '18 copy fid.html#imageeval.fid',
                                                                                      'diy_stable_diffusion/fid.py'),
                                          'diy_stable_diffusion.fid.ImageEval.get_feats': ( '18 copy fid.html#imageeval.get_feats',
                                                                                            'diy_stable_diffusion/fid.py'),
                                          'diy_stable_diffusion.fid.ImageEval.kid': ( '18 copy fid.html#imageeval.kid',
                                                                                      'diy_stable_diffusion/fid.py'),
                                          'diy_stable_diffusion.fid._calc_fid': ( '18 copy fid.html#_calc_fid',
                                                                                  'diy_stable_diffusion/fid.py'),
                                          'diy_stable_diffusion.fid._calc_kid': ( '18 copy fid.html#_calc_kid',
                                                                                  'diy_stable_diffusion/fid.py'),
                                          'diy_stable_diffusion.fid._calc_stats': ( '18 copy fid.html#_calc_stats',
                                                                                    'diy_stable_diffusion/fid.py'),
                                          'diy_stable_diffusion.fid._sqrtm_newton_schulz': ( '18 copy fid.html#_sqrtm_newton_schulz',
                                                                                             'diy_stable_diffusion/fid.py'),
                                          'diy_stable_diffusion.fid._squared_mmd': ( '18 copy fid.html#_squared_mmd',
                                                                                     'diy_stable_diffusion/fid.py')},
            'diy_stable_diffusion.init': { 'diy_stable_diffusion.init.BatchTransformCB': ( '11 copy initialization.html#batchtransformcb',
                                                                                           'diy_stable_diffusion/init.py'),
                                           'diy_stable_diffusion.init.BatchTransformCB.__init__': ( '11 copy '
                                                                                                    'initialization.html#batchtransformcb.__init__',
                                                                                                    'diy_stable_diffusion/init.py'),
                                           'diy_stable_diffusion.init.BatchTransformCB.before_batch': ( '11 copy '
                                                                                                        'initialization.html#batchtransformcb.before_batch',
                                                                                                        'diy_stable_diffusion/init.py'),
                                           'diy_stable_diffusion.init.GeneralRelu': ( '11 copy initialization.html#generalrelu',
                                                                                      'diy_stable_diffusion/init.py'),
                                           'diy_stable_diffusion.init.GeneralRelu.__init__': ( '11 copy '
                                                                                               'initialization.html#generalrelu.__init__',
                                                                                               'diy_stable_diffusion/init.py'),
                                           'diy_stable_diffusion.init.GeneralRelu.forward': ( '11 copy '
                                                                                              'initialization.html#generalrelu.forward',
                                                                                              'diy_stable_diffusion/init.py'),
                                           'diy_stable_diffusion.init._lsuv_stats': ( '11 copy initialization.html#_lsuv_stats',
                                                                                      'diy_stable_diffusion/init.py'),
                                           'diy_stable_diffusion.init.clean_ipython_hist': ( '11 copy '
                                                                                             'initialization.html#clean_ipython_hist',
                                                                                             'diy_stable_diffusion/init.py'),
                                           'diy_stable_diffusion.init.clean_mem': ( '11 copy initialization.html#clean_mem',
                                                                                    'diy_stable_diffusion/init.py'),
                                           'diy_stable_diffusion.init.clean_tb': ( '11 copy initialization.html#clean_tb',
                                                                                   'diy_stable_diffusion/init.py'),
                                           'diy_stable_diffusion.init.conv': ( '11 copy initialization.html#conv',
                                                                               'diy_stable_diffusion/init.py'),
                                           'diy_stable_diffusion.init.get_model': ( '11 copy initialization.html#get_model',
                                                                                    'diy_stable_diffusion/init.py'),
                                           'diy_stable_diffusion.init.init_weights': ( '11 copy initialization.html#init_weights',
                                                                                       'diy_stable_diffusion/init.py'),
                                           'diy_stable_diffusion.init.lsuv_init': ( '11 copy initialization.html#lsuv_init',
                                                                                    'diy_stable_diffusion/init.py'),
                                           'diy_stable_diffusion.init.plot_func': ( '11 copy initialization.html#plot_func',
                                                                                    'diy_stable_diffusion/init.py')},
            'diy_stable_diffusion.learner': { 'diy_stable_diffusion.learner.Callback': ( '09 copy learner.html#callback',
                                                                                         'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.Callback.__getattr__': ( '09 copy '
                                                                                                     'learner.html#callback.__getattr__',
                                                                                                     'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.Callback.__setattr__': ( '09 copy '
                                                                                                     'learner.html#callback.__setattr__',
                                                                                                     'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.Callback.training': ( '09 copy learner.html#callback.training',
                                                                                                  'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.CancelBatchException': ( '09 copy '
                                                                                                     'learner.html#cancelbatchexception',
                                                                                                     'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.CancelEpochException': ( '09 copy '
                                                                                                     'learner.html#cancelepochexception',
                                                                                                     'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.CancelFitException': ( '09 copy '
                                                                                                   'learner.html#cancelfitexception',
                                                                                                   'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.DeviceCB': ( '09 copy learner.html#devicecb',
                                                                                         'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.DeviceCB.__init__': ( '09 copy learner.html#devicecb.__init__',
                                                                                                  'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.DeviceCB.before_batch': ( '09 copy '
                                                                                                      'learner.html#devicecb.before_batch',
                                                                                                      'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.DeviceCB.before_fit': ( '09 copy '
                                                                                                    'learner.html#devicecb.before_fit',
                                                                                                    'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.LRFinderCB': ( '09 copy learner.html#lrfindercb',
                                                                                           'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.LRFinderCB.__init__': ( '09 copy '
                                                                                                    'learner.html#lrfindercb.__init__',
                                                                                                    'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.LRFinderCB.after_batch': ( '09 copy '
                                                                                                       'learner.html#lrfindercb.after_batch',
                                                                                                       'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.LRFinderCB.before_fit': ( '09 copy '
                                                                                                      'learner.html#lrfindercb.before_fit',
                                                                                                      'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.LRFinderCB.cleanup_fit': ( '09 copy '
                                                                                                       'learner.html#lrfindercb.cleanup_fit',
                                                                                                       'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.Learner': ( '09 copy learner.html#learner',
                                                                                        'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.Learner.__getattr__': ( '09 copy '
                                                                                                    'learner.html#learner.__getattr__',
                                                                                                    'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.Learner.__init__': ( '09 copy learner.html#learner.__init__',
                                                                                                 'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.Learner._fit': ( '09 copy learner.html#learner._fit',
                                                                                             'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.Learner._one_batch': ( '09 copy '
                                                                                                   'learner.html#learner._one_batch',
                                                                                                   'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.Learner._one_epoch': ( '09 copy '
                                                                                                   'learner.html#learner._one_epoch',
                                                                                                   'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.Learner.callback': ( '09 copy learner.html#learner.callback',
                                                                                                 'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.Learner.fit': ( '09 copy learner.html#learner.fit',
                                                                                            'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.Learner.one_epoch': ( '09 copy learner.html#learner.one_epoch',
                                                                                                  'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.Learner.training': ( '09 copy learner.html#learner.training',
                                                                                                 'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.MetricsCB': ( '09 copy learner.html#metricscb',
                                                                                          'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.MetricsCB.__init__': ( '09 copy '
                                                                                                   'learner.html#metricscb.__init__',
                                                                                                   'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.MetricsCB._log': ( '09 copy learner.html#metricscb._log',
                                                                                               'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.MetricsCB.after_batch': ( '09 copy '
                                                                                                      'learner.html#metricscb.after_batch',
                                                                                                      'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.MetricsCB.after_epoch': ( '09 copy '
                                                                                                      'learner.html#metricscb.after_epoch',
                                                                                                      'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.MetricsCB.before_epoch': ( '09 copy '
                                                                                                       'learner.html#metricscb.before_epoch',
                                                                                                       'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.MetricsCB.before_fit': ( '09 copy '
                                                                                                     'learner.html#metricscb.before_fit',
                                                                                                     'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.MomentumLearner': ( '09 copy learner.html#momentumlearner',
                                                                                                'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.MomentumLearner.__init__': ( '09 copy '
                                                                                                         'learner.html#momentumlearner.__init__',
                                                                                                         'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.MomentumLearner.zero_grad': ( '09 copy '
                                                                                                          'learner.html#momentumlearner.zero_grad',
                                                                                                          'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.ProgressCB': ( '09 copy learner.html#progresscb',
                                                                                           'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.ProgressCB.__init__': ( '09 copy '
                                                                                                    'learner.html#progresscb.__init__',
                                                                                                    'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.ProgressCB._log': ( '09 copy learner.html#progresscb._log',
                                                                                                'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.ProgressCB.after_batch': ( '09 copy '
                                                                                                       'learner.html#progresscb.after_batch',
                                                                                                       'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.ProgressCB.after_epoch': ( '09 copy '
                                                                                                       'learner.html#progresscb.after_epoch',
                                                                                                       'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.ProgressCB.before_epoch': ( '09 copy '
                                                                                                        'learner.html#progresscb.before_epoch',
                                                                                                        'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.ProgressCB.before_fit': ( '09 copy '
                                                                                                      'learner.html#progresscb.before_fit',
                                                                                                      'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.SingleBatchCB': ( '09 copy learner.html#singlebatchcb',
                                                                                              'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.SingleBatchCB.after_batch': ( '09 copy '
                                                                                                          'learner.html#singlebatchcb.after_batch',
                                                                                                          'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.TrainCB': ( '09 copy learner.html#traincb',
                                                                                        'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.TrainCB.__init__': ( '09 copy learner.html#traincb.__init__',
                                                                                                 'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.TrainCB.backward': ( '09 copy learner.html#traincb.backward',
                                                                                                 'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.TrainCB.get_loss': ( '09 copy learner.html#traincb.get_loss',
                                                                                                 'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.TrainCB.predict': ( '09 copy learner.html#traincb.predict',
                                                                                                'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.TrainCB.step': ( '09 copy learner.html#traincb.step',
                                                                                             'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.TrainCB.zero_grad': ( '09 copy learner.html#traincb.zero_grad',
                                                                                                  'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.TrainLearner': ( '09 copy learner.html#trainlearner',
                                                                                             'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.TrainLearner.backward': ( '09 copy '
                                                                                                      'learner.html#trainlearner.backward',
                                                                                                      'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.TrainLearner.get_loss': ( '09 copy '
                                                                                                      'learner.html#trainlearner.get_loss',
                                                                                                      'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.TrainLearner.predict': ( '09 copy '
                                                                                                     'learner.html#trainlearner.predict',
                                                                                                     'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.TrainLearner.step': ( '09 copy learner.html#trainlearner.step',
                                                                                                  'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.TrainLearner.zero_grad': ( '09 copy '
                                                                                                       'learner.html#trainlearner.zero_grad',
                                                                                                       'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.lr_find': ( '09 copy learner.html#lr_find',
                                                                                        'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.run_cbs': ( '09 copy learner.html#run_cbs',
                                                                                        'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.to_cpu': ( '09 copy learner.html#to_cpu',
                                                                                       'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.with_cbs': ( '09 copy learner.html#with_cbs',
                                                                                         'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.with_cbs.__call__': ( '09 copy learner.html#with_cbs.__call__',
                                                                                                  'diy_stable_diffusion/learner.py'),
                                              'diy_stable_diffusion.learner.with_cbs.__init__': ( '09 copy learner.html#with_cbs.__init__',
                                                                                                  'diy_stable_diffusion/learner.py')},
            'diy_stable_diffusion.resnet': { 'diy_stable_diffusion.resnet.ResBlock': ( '13 copy resnets.html#resblock',
                                                                                       'diy_stable_diffusion/resnet.py'),
                                             'diy_stable_diffusion.resnet.ResBlock.__init__': ( '13 copy resnets.html#resblock.__init__',
                                                                                                'diy_stable_diffusion/resnet.py'),
                                             'diy_stable_diffusion.resnet.ResBlock.forward': ( '13 copy resnets.html#resblock.forward',
                                                                                               'diy_stable_diffusion/resnet.py'),
                                             'diy_stable_diffusion.resnet._conv_block': ( '13 copy resnets.html#_conv_block',
                                                                                          'diy_stable_diffusion/resnet.py')},
            'diy_stable_diffusion.sgd': { 'diy_stable_diffusion.sgd.BaseSchedCB': ( '12 copy accelerated sgd.html#baseschedcb',
                                                                                    'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.BaseSchedCB.__init__': ( '12 copy accelerated '
                                                                                             'sgd.html#baseschedcb.__init__',
                                                                                             'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.BaseSchedCB._step': ( '12 copy accelerated sgd.html#baseschedcb._step',
                                                                                          'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.BaseSchedCB.before_fit': ( '12 copy accelerated '
                                                                                               'sgd.html#baseschedcb.before_fit',
                                                                                               'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.BatchSchedCB': ( '12 copy accelerated sgd.html#batchschedcb',
                                                                                     'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.BatchSchedCB.after_batch': ( '12 copy accelerated '
                                                                                                 'sgd.html#batchschedcb.after_batch',
                                                                                                 'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.EpochSchedCB': ( '12 copy accelerated sgd.html#epochschedcb',
                                                                                     'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.EpochSchedCB.after_epoch': ( '12 copy accelerated '
                                                                                                 'sgd.html#epochschedcb.after_epoch',
                                                                                                 'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.HasLearnCB': ( '12 copy accelerated sgd.html#haslearncb',
                                                                                   'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.HasLearnCB.after_fit': ( '12 copy accelerated '
                                                                                             'sgd.html#haslearncb.after_fit',
                                                                                             'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.HasLearnCB.before_fit': ( '12 copy accelerated '
                                                                                              'sgd.html#haslearncb.before_fit',
                                                                                              'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.RecorderCB': ( '12 copy accelerated sgd.html#recordercb',
                                                                                   'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.RecorderCB.__init__': ( '12 copy accelerated '
                                                                                            'sgd.html#recordercb.__init__',
                                                                                            'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.RecorderCB.after_batch': ( '12 copy accelerated '
                                                                                               'sgd.html#recordercb.after_batch',
                                                                                               'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.RecorderCB.before_fit': ( '12 copy accelerated '
                                                                                              'sgd.html#recordercb.before_fit',
                                                                                              'diy_stable_diffusion/sgd.py'),
                                          'diy_stable_diffusion.sgd.RecorderCB.plot': ( '12 copy accelerated sgd.html#recordercb.plot',
                                                                                        'diy_stable_diffusion/sgd.py')},
            'diy_stable_diffusion.training': { 'diy_stable_diffusion.training.DataLoader': ( '04 copy minibatch_training.html#dataloader',
                                                                                             'diy_stable_diffusion/training.py'),
                                               'diy_stable_diffusion.training.DataLoader.__init__': ( '04 copy '
                                                                                                      'minibatch_training.html#dataloader.__init__',
                                                                                                      'diy_stable_diffusion/training.py'),
                                               'diy_stable_diffusion.training.DataLoader.__iter__': ( '04 copy '
                                                                                                      'minibatch_training.html#dataloader.__iter__',
                                                                                                      'diy_stable_diffusion/training.py'),
                                               'diy_stable_diffusion.training.Dataset': ( '04 copy minibatch_training.html#dataset',
                                                                                          'diy_stable_diffusion/training.py'),
                                               'diy_stable_diffusion.training.Dataset.__getitem__': ( '04 copy '
                                                                                                      'minibatch_training.html#dataset.__getitem__',
                                                                                                      'diy_stable_diffusion/training.py'),
                                               'diy_stable_diffusion.training.Dataset.__init__': ( '04 copy '
                                                                                                   'minibatch_training.html#dataset.__init__',
                                                                                                   'diy_stable_diffusion/training.py'),
                                               'diy_stable_diffusion.training.Dataset.__len__': ( '04 copy '
                                                                                                  'minibatch_training.html#dataset.__len__',
                                                                                                  'diy_stable_diffusion/training.py'),
                                               'diy_stable_diffusion.training.accuracy': ( '04 copy minibatch_training.html#accuracy',
                                                                                           'diy_stable_diffusion/training.py'),
                                               'diy_stable_diffusion.training.fit': ( '04 copy minibatch_training.html#fit',
                                                                                      'diy_stable_diffusion/training.py'),
                                               'diy_stable_diffusion.training.get_dls': ( '04 copy minibatch_training.html#get_dls',
                                                                                          'diy_stable_diffusion/training.py'),
                                               'diy_stable_diffusion.training.report': ( '04 copy minibatch_training.html#report',
                                                                                         'diy_stable_diffusion/training.py')},
            'diy_stable_diffusion.utils': {'diy_stable_diffusion.utils.saveobj': ('utils.html#saveobj', 'diy_stable_diffusion/utils.py')}}}
