# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/18 copy fid.ipynb.

# %% auto 0
__all__ = ['ImageEval']

# %% ../nbs/18 copy fid.ipynb 1
import pickle,gzip,math,os,time,shutil,torch,random
import fastcore.all as fc,matplotlib as mpl,numpy as np,matplotlib.pyplot as plt
from collections.abc import Mapping
from pathlib import Path
from operator import attrgetter,itemgetter
from functools import partial
from copy import copy
from contextlib import contextmanager
from scipy import linalg

from fastcore.foundation import L
import torchvision.transforms.functional as TF,torch.nn.functional as F
from torch import tensor,nn,optim
from torch.utils.data import DataLoader,default_collate
from torch.nn import init
from torch.optim import lr_scheduler
from torcheval.metrics import MulticlassAccuracy
from datasets import load_dataset,load_dataset_builder

from .datasets import *
from .conv import *
from .learner import *
from .activations import *
from .init import *
from .sgd import *
from .resnet import *
from .augment import *
from .accel import *

# %% ../nbs/18 copy fid.ipynb 23
def _sqrtm_newton_schulz(mat, num_iters=100):
    mat_norm = mat.norm()
    mat = mat.double()
    Y = mat/mat_norm
    n = len(mat)
    I = torch.eye(n).to(mat)
    Z = torch.eye(n).to(mat)
    
    for i in range(num_iters):
        T = (3*I - Z@Y) / 2
        Y = Y@T
        Z = T@Z
        res = Y*mat_norm.sqrt()
        
        if ((mat - (res @ res)).norm() / mat_norm).abs() <=1e-6:
            break
    
    return res

# %% ../nbs/18 copy fid.ipynb 24
def _calc_stats(feats):
    feats = feats.squeeze()
    return feats.mean(0), feats.T.cov()

def _calc_fid(means1, covs1, means2, covs2):
    csr = tensor(linalg.sqrtm(covs1@covs2, 256).real)
    '''
    return (
        ((means1 - means2)**2).sum() +
        covs1.trace() + covs2.trace() - 2*csr.trace()
    ).item()
    '''
    return (((means1-means2)**2).sum() + covs1.trace() + covs2.trace() - 2*csr.trace()).item()

# %% ../nbs/18 copy fid.ipynb 34
def _squared_mmd(x, y):
    def kernel(a, b):
        return ((a@b.transpose(-2, -1) / a.shape[-1]) + 1)**3
    
    m, n = x.shape[-2], y.shape[-2]
    kxx, kyy, kxy = kernel(x,x), kernel(y, y), kernel(x, y)
    kxx_sum = kxx.sum([-1, -2]) - kxx.diagonal(0, -1, -2).sum(-1)
    kyy_sum = kyy.sum([-1, -2]) - kyy.diagonal(0, -1, -2).sum(-1)
    kxy_sum = kxy.sum([-1, -2])
    
    return (
        kxx_sum / (m * (m-1)) +
        kyy_sum / (n * (n-1)) -
        kxy_sum*2 / (m * n)
    )

# %% ../nbs/18 copy fid.ipynb 35
def _calc_kid(x, y, maxs=50):
    xs, ys = x.shape[0], y.shape[0]
    n= max(math.ceil(min(xs/maxs, ys/maxs)), 4)
    mmd = 0.0
    for i in range(n):
        cur_x = x[round(i*xs / n) : round((i+1)*xs / n)]
        cur_y = y[round(i*ys / n) : round((i+1)*ys / n)]
        mmd += _squared_mmd(cur_x, cur_y)
    return (mmd/n).item()

# %% ../nbs/18 copy fid.ipynb 37
class ImageEval:
    def __init__(self, model, dls, cbs):
        self.learn=TrainLearner(model, dls, loss_func=fc.noop, cbs=cbs, opt_func=None)
        self.feats = self.learn.capture_preds()[0].float().cpu().squeeze()
        self.stats = _calc_stats(self.feats)
    
    def get_feats(self, samples):
        self.learn.dls = DataLoaders([], [(samples, torch.zeros((0,)))])
        return self.learn.capture_preds()[0].float().cpu().squeeze()
    
    def fid(self, samples):
        feats = self.get_feats(samples)
        return _calc_fid(*self.stats, *_calc_stats(feats))
    
    def kid(self, samples):
        feats = self.get_feats(samples)
        return _calc_kid(self.feats, feats)
