# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto 0
__all__ = ['saveobj']

# %% ../nbs/utils.ipynb 1
import datetime
import torch

# %% ../nbs/utils.ipynb 2
'''
save obj to models/{date}-{name}-{randstr}.pkl'
'''
def saveobj(obj, name):
    now = datetime.datetime.now()
    date = now.date().isoformat()
    randstr = hex(abs(hash(now))).replace('0x', '')[:8]
    filepath=f'models/{date}-{name}-{randstr}.pkl'
    torch.save(obj, filepath)
    print(filepath)
